whodunnit:
  target: local
  outputs:
    docker:
      type: postgres
      host: "host.docker.internal"
      user: "{{ env_var('DBT_ENV_SECRET_USER') }}"
      password: "{{ env_var('DBT_ENV_SECRET_PASSWORD') }}"
      port: 5432
      dbname: "postgres"
      schema : "whodunnit"
      threads: 4

    sqlfluff:
      type: postgres
      host: "localhost"
      user: "postgres"
      password: "postgres"
      port: 5432
      dbname: "postgres"
      schema: "whodunnit"
      threads: 1
    
    elementary:
      outputs:
        default:
          type: postgres
          host: localhost
          port: 5432
          user: "postgres"
          password: "postgres"
          dbname: "postgres"
          schema: whodunnit_elementary
          threads: 4
  
    local:
      type: postgres
      host: "localhost"
      user: "{{ env_var('DBT_ENV_SECRET_USER') }}"
      password: "{{ env_var('DBT_ENV_SECRET_PASSWORD') }}"
      port: 5432
      dbname: "postgres"
      schema : "whodunnit"
      threads: 4