version: '3.9'

secrets:
  psql_user:
    file: ./psql_user.txt
  psql_password:
    file: ./psql_password.txt

services:
  pgloader-sqlite:
    image: dimitri/pgloader
    volumes: 
    - "./init-db:/opt/db"
    - "./pgloader-config:/loader"
    command: pgloader https://mystery.knightlab.com/sql-murder-mystery.db postgresql://postgres:postgres@postgres:5432/postgres
    depends_on:
      postgres: 
              condition: service_healthy
    networks:
      - postgres
  postgres:
    container_name: postgres_container_x
    image: postgres
    restart: always
    environment:
       POSTGRES_USER_FILE: /run/secrets/psql_user
       POSTGRES_PASSWORD_FILE: /run/secrets/psql_password
       POSTGRES_DB: postgres
       PGDATA: /var/lib/postgresql/datas
    secrets:
      - psql_user
      - psql_password
    volumes:
       - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3
  pgadmin:
    container_name: pgadmin4_container_x
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
    volumes:
      - postgres:/var/lib/pgadmin/data
    depends_on:
      - postgres 
    networks:
      - postgres


  # metabase:
  #   container_name: metabase_container
  #   image: metabase/metabase:latest
  #   environment:
  #      MB_DB_TYPE: postgres
  #      MB_DB_DBNAME: postgres
  #      MB_DB_PORT: 5432
  #      MB_DB_USER: postgres
  #      MB_DB_PASS: postgres
  #      MB_DB_HOST: postgres
  #   volumes:
  #     - postgres:/var/lib/metabase/data
  #   ports:
  #     - 3000:3000
  #   restart: always
  #   depends_on:
  #     - postgres
  #   networks:
  #     - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
        driver: local
