name: schedule_dbt_run

on:
  schedule:
    # run at 7AM every single day
    # https://crontab.guru <-- for generating CRON expression
    - cron: '0 7 * * *'
  push:
    branches:
    # run on push to development branch
    - development
env:
    DBT_PROFILES_DIR: ./

    DBT_POSTGRES_USER: ${{ secrets.DBT_POSTGRES_USER }}
    DBT_POSTGRES_PASSWORD: ${{ secrets.DBT_POSTGRES_PASSWORD }}
    DBT_POSTGRE_DB: ${{ secrets.DBT_POSTGRE_DB }}

jobs:
 schedule_dbt_run:
    name: schedule_dbt_run
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: "actions/checkout@master"

      - uses: "actions/setup-python@v4"
        with:
         python-version: "3.10"

      - name: Install dependencies
        run: |
            pip install dbt-postgres
            dbt deps --project-dir ./whodunnit

    # dbt related commands here - run use --target prod/dev to run for specific environments
      - name: Run dbt models
        run: dbt run --target main --project-dir ./whodunnit

      - name: Test dbt models
        run: dbt test --target main --project-dir ./whodunnit
